# Generated by Django 6.0 on 2026-01-05 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('level', models.IntegerField(default=1)),
                ('role', models.CharField(default='Scholar', max_length=50)),
                ('current_goal', models.CharField(blank=True, max_length=255)),
                ('avg_score', models.IntegerField(default=0)),
                ('quizzes_done', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
